<?php
	/*
	 * Wordpress Github Repos Class
	 */

	class WP_My_Github_Repos extends WP_Widget {
		// Create Widget
		function __construct() {
			parent::__construct(
				'my_github_repos', // base id
				__('My Github Repos', 'mgr_domain'), // name
				array('description' => __('A Github Repository Widget', 'mgr_domain')) // description
			);
		}

		// Frontend Display
		public function widget($args, $instance) {

		}

		// Backend Form
		public function form( $instance ) {
			// Get Title
			if(isset($instance['title'])) {
				$title = $instance['title'];
			} else {
				$title = __('Latest Github Projects', 'mgr_domain');
			}

			// Get Username
			if(isset($instance['username'])) {
				$username = $instance['username'];
			} else {
				$username = __('henroben', 'mgr_domain');
			}

			// Count for repositories to show
			if(isset($instance['count'])) {
				$count = $instance['count'];
			} else {
				$count = 5;
			}
			?>
				<p>
					<label for="<?php echo $this->get_field_id('title'); ?>"><?php _e('Title', 'mgr_domain'); ?></label>
					<input type="text" class="widefat" id="<?php echo $this->get_field_id('title'); ?>" name="<?php echo $this->get_field_name('title'); ?>" value="<?php echo esc_html($title); ?>">
				</p>

				<p>
					<label for="<?php echo $this->get_field_id('username'); ?>"><?php _e('Username', 'mgr_domain'); ?></label>
					<input type="text" class="widefat" id="<?php echo $this->get_field_id('username'); ?>" name="<?php echo $this->get_field_name('username'); ?>" value="<?php echo esc_html($username); ?>">
				</p>

				<p>
					<label for="<?php echo $this->get_field_id('count'); ?>"><?php _e('Repos to display', 'mgr_domain'); ?></label>
					<input type="text" class="widefat" id="<?php echo $this->get_field_id('count'); ?>" name="<?php echo $this->get_field_name('count'); ?>" value="<?php echo esc_html($count); ?>">
				</p>
			<?php
		}

		// Update Widget Values
		public function update( $new_instance, $old_instance ) {
			return parent::update( $new_instance, $old_instance ); // TODO: Change the autogenerated stub
		}
	}